name: TPO
version: 2.0
author: Jannify


main: de.Jannify.ErstesPlugin.TPO

commands:
  tpo:
    description: Öffnet das Creativ Menü
    usage: /tpo oder /tpo get
    permission: TPO.menu.open